set nocompatible
set number
set relativenumber
set ttimeoutlen=50 "Tiempo escape
set timeoutlen=1000 "Tiempo siguiente comando
set showcmd "Muestra comando incompleto
set wildmenu "Autocompletado menu
set mouse=a "Soporte mouse
set cursorline "Resalta la linea que estoy
set backspace=indent,eol,start "Para poder borrar con backspace

filetype indent plugin on
syntax on

set undofile
set undodir=~/.vim/undodir

set noswapfile "desactiva los archivos Swap
set nobackup   "no se crean respaldos permanentes cuando se guarda un archivo
set nowritebackup "no se crean respaldos temporales al guardar archivos

set ignorecase "busquedas no distinguen mayusculas y minusculas
set incsearch   "Muestra la concordancia de una busqueda mientras escribes.
set hlsearch    "Resalta las busquedas

colorscheme gruvbox

"""" Atajos utiles, cuando te equivocas escribiendo alguno de estos comandos
"ejemplo :w para guardar, si escribes rapido posiblemente escribas :W
cnoreabbrev W w
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev Qall! qall!
cnoreabbrev Wq wq
cnoreabbrev Wa wa
cnoreabbrev wQ wq
cnoreabbrev WQ wq
cnoreabbrev Q q
cnoreabbrev Qall qall

let mapleader = ","
let &t_SI = "\<Esc>[6 q"
let &t_EI = "\<Esc>[2 q"

nnoremap <F2> :Autoformat<CR>
