#!/usr/bin/perl -w
use strict;
use warnings;

my $memoria = `free -m`;
$memoria =~ s/.*mem:\s*|swap:.*//si;
$memoria =~ s/\d+\s+(\d+).*/$1/;

printf "%.2Gf%%\n", $memoria;
printf "%.2Gf%%\n", $memoria;

exit 0;
